server:
  port: 8081

jwt:
  secret: your-super-strong-secret-key-that-is-at-least-256-bits-long-for-hs256
  expiration-ms: 86400000 # 24 hours

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Deng2846240558
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect